accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import (
    register,
    index,
    update_user,
    update_password,
)

app_name = 'accounts'

urlpatterns = [
    path('', index, name='index'),

    path('entrar/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('sair/', LogoutView.as_view(), name='logout'),

    path('registrar/', register, name='register'),
    path('alterar-dados/', update_user, name='update_user'),
    path('alterar-senha/', update_password, name='update_password'),
]

catalog/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import (
    product_list,
    category,
    product,
)

app_name = 'catalog'

urlpatterns = [
    path('', product_list, name='products'),
    path('<slug:slug>/', category, name='category'),
    path('produtos/<slug:slug>/', product, name='product'),
]

checkout/urls.py
from django.urls import path

from .views import (
    create_cartitem,
    cart_item,
    checkout,
    order_list,
    order_detail,
)

app_name = 'checkout'

urlpatterns = [
    path('carrinho/adicionar/<slug:slug>/', create_cartitem, name='create_cartitem'),
    path('carrinho/', cart_item, name='cart_item'),
    path('finalizando/', checkout, name='checkout'),
    path('meus-pedidos/', order_list, name='order_list'),
    path('meus-pedidos/<int:pk>', order_detail, name='order_detail'),
]

core/urls.py
from django.urls import path

from .views import (
    index,
    contact,
)

app_name = 'core'

urlpatterns = [
    path('', index, name="index"),
    
    path('contato/', contact, name='contact'),
]

djangoecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('catalogo/', include('catalog.urls', namespace='catalog')),
    path('admin/', admin.site.urls, name='admin'),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings


class ContactForm(forms.Form):

    name = forms.CharField(label='Nome')
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(label='Mensagem', widget=forms.Textarea())

    def send_mail(self):
        name = self.cleaned_data['name']
        email  = self.cleaned_data['email']
        message = self.cleaned_data['message']

        message = '{} | {}\n\n{}'.format(name, email, message)

        send_mail(
            'Contato do Eco Django', message, settings.DEFAULT_FROM_EMAIL,
            [settings.DEFAULT_FROM_EMAIL]
        )

core/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.views.generic import TemplateView
from django.contrib import messages

from .forms import ContactForm

# Create your views here.
class IndexView(TemplateView):

    template_name = 'core/index.html'


def contact(request):
    success = False
    form = ContactForm(request.POST or None)

    if form.is_valid():
        form.send_mail()
        success = True
    elif request.method == 'POST':
        messages.error(request, 'Formulário inválido!')
    
    context = {
        'form' : form,
        'success' : success
    }
    
    return render(request, 'core/contact.html', context)


index = IndexView.as_view()

templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% comment %} <link rel="stylesheet" href="https://bootswatch.com/4/flatly/bootstrap.css" media="screen"> {% endcomment %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'core/css/style.css' %}">

    <title>{% block title %}Django E-Commerce{% endblock %}</title>
</head>
<body id="topo">
    <div class="container">
        <!-- Menu de Navegação -->
        <div class="row">
            <div class="col">
                <header>
                    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
                        <a class="navbar-brand" href="{% url 'core:index' %}">Django E-Commerce</a>
                    
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMain" aria-controls="navbarMain" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                    
                        <div class="collapse navbar-collapse" id="navbarMain">
                            <ul class="navbar-nav mr-auto">
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                                </li>

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categorias</a>
                                    
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="{% url 'catalog:products' %}">* TODOS *</a>

                                        {% for category in categories %}
                                            <a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category }}</a>
                                        {% endfor %}
                                    </div>
                                </li>
                    
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'core:contact' %}">Contato</a>
                                </li>
                            </ul>
                    
                            <ul class="navbar-nav navbar-right">
                                {% if user.is_authenticated %}
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'accounts:index' %}">Minha Conta</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'accounts:logout' %}">Sair</a>
                                    </li>
                                {% else %}
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'accounts:register' %}">Registrar</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'accounts:login' %}">Entrar</a>
                                    </li>
                                {% endif %}

                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'checkout:cart_item' %}">Carrinho</a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </header>
            </div>
        </div>

        <!-- Conteúdo da Página -->
        {% block messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endblock %}

        {% block main %}
        {% endblock %}

        <!-- Rodapé -->
        <div class="row">
            <div class="col">
                <footer id="footer">
                    <nav class="navbar">
                        <ul class="list-unstyled" style="width:100%">
                            <li class="float-right"><a class="nav-link" href="#topo">Voltar ao Topo</a></li>
                            
                            <li><a class="nav-link" href="{% url 'core:index' %}">Início</a></li>
                            <li><a class="nav-link" href="{% url 'catalog:products' %}">Produtos</a></li>
                            <li><a class="nav-link" href="{% url 'core:contact' %}">Contato</a></li>
                            <li><a class="nav-link" href="#">Termos e Privacidade</a></li>
                        </ul>
                    </nav>
                </footer id="footer">
            </div>
        </div>
    </div>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <!-- <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script> -->
</body>
</html>

templates/core/contact.html
{% extends 'core/base.html' %}

{% load widget_tweaks %}

{% block title %}
    Contato | {{ block.super }}
{% endblock %}

{% block main %}
    <div class="row">
        <div class="col">
            <div class="page-header">
                <h1>Fale conosco</h1>
            </div>

            {% if success %}
                <div class="alert alert-success" role="alert">Mensagem enviada com sucesso</div>
            {% endif %}

            <form action="" method="POST">
                {% csrf_token %}

                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                        
                        <div class="col-md-9">
                            {% render_field field class+='form-control' %}
                        </div>
                    </div>
                {% endfor %}

                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-dark">Enviar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/core/contato.html
{% extends 'core/base.html' %}

{% block title %}
    Contato | {{ block.super }}
{% endblock %}

{% block main %}
    <div class="row">
        <div class="col">
            <div class="page-header">
                <h1>Fale conosco</h1>
            </div>

            <form>
                <div class="form-group">
                    <label for="id_name" class="col-md-3 control-label">Nome</label>
                    
                    <div class="col-md-9">
                        <input type="text" class="form-control" id="id_name" placeholder="Nome" />
                    </div>
                </div>

                <div class="form-group">
                    <label for="id_email" class="col-md-3 control-label">E-mail</label>
                    
                    <div class="col-md-9">
                        <input type="text" class="form-control" id="id_email" placeholder="E-mail" />
                    </div>
                </div>

                <div class="form-group has-error">
                    <label for="id_message" class="col-md-3 control-label">Mensagem</label>
                    
                    <div class="col-md-9">
                        <textarea class="form-control" rows="3" id="id_message" required></textarea>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-dark">Enviar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/core/index.html
{% extends 'core/base.html' %}

{% block main %}
    <div class="row">
        <div class="col">
            <div class="jumbotron">
                <div class="page-header">
                    <h1>Django E-Commerce</h1>
                </div>
            
                <p class="lead">
                    Mussum Ipsum, cacilds vidis litro abertis.
                    Nullam volutpat risus nec leo commodo, ut interdum diam laoreet.
                    Sed non consequat odio. Interagi no mé, cursus quis, vehicula ac nisi.
                </p>
                
                <a class="btn btn-dark btn-lg" href="#" role="button">Saiba mais</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/core/produto.html
{% extends 'core/base.html' %}

{% block title %}
    Produto | {{ block.super }}
{% endblock %}

{% block main %}
    <div class="row">
        <div class="col">
            <div class="page-header">
                <h1>Página do Produto</h1>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-4">
            <img src="http://placehold.it/350x250" class="img-fluid img-thumbnail" alt="Responsive image">
        </div>

        <div class="col-sm-8">
            <dl>
                <dt>Lorem ipsum:</dt>
                <dd>Lorem ipsum dolor sit amet</dd>

                <dt>Lorem ipsum:</dt>
                <dd>Lorem ipsum dolor sit amet</dd>

                <dt>Lorem ipsum:</dt>
                <dd>Lorem ipsum dolor sit amet</dd>

                <dt>Lorem ipsum:</dt>
                <dd>Lorem ipsum dolor sit amet</dd>

                <dt>Lorem ipsum:</dt>
                <dd>Lorem ipsum dolor sit amet</dd>
            </dl>
        </div>
    </div>
{% endblock %}