accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import (
    register,
    index,
    update_user,
    update_password,
)

app_name = 'accounts'

urlpatterns = [
    path('', index, name='index'),

    path('entrar/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('sair/', LogoutView.as_view(), name='logout'),

    path('registrar/', register, name='register'),
    path('alterar-dados/', update_user, name='update_user'),
    path('alterar-senha/', update_password, name='update_password'),
]

catalog/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import (
    product_list,
    category,
    product,
)

app_name = 'catalog'

urlpatterns = [
    path('', product_list, name='products'),
    path('<slug:slug>/', category, name='category'),
    path('produtos/<slug:slug>/', product, name='product'),
]

checkout/urls.py
from django.urls import path

from .views import (
    create_cartitem,
    cart_item,
    checkout,
    order_list,
    order_detail,
)

app_name = 'checkout'

urlpatterns = [
    path('carrinho/adicionar/<slug:slug>/', create_cartitem, name='create_cartitem'),
    path('carrinho/', cart_item, name='cart_item'),
    path('finalizando/', checkout, name='checkout'),
    path('meus-pedidos/', order_list, name='order_list'),
    path('meus-pedidos/<int:pk>', order_detail, name='order_detail'),
]

core/urls.py
from django.urls import path

from .views import (
    index,
    contact,
)

app_name = 'core'

urlpatterns = [
    path('', index, name="index"),
    
    path('contato/', contact, name='contact'),
]

djangoecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('catalogo/', include('catalog.urls', namespace='catalog')),
    path('admin/', admin.site.urls, name='admin'),
]

checkout/models.py
from django.db import models
from django.conf import settings

from catalog.models import Product

# Create your models here.


class CartItemManager(models.Manager):

    def add_item(self, cart_key, product):
        if self.filter(cart_key=cart_key, product=product).exists():
            created = False
            cart_item = self.get(cart_key=cart_key, product=product)
            cart_item.quantity += 1
            cart_item.save()
        else:
            created = True
            cart_item = CartItem.objects.create(
                cart_key=cart_key,
                product=product,
                price=product.price
            )
    
        return cart_item, created


class CartItem(models.Model):

    cart_key = models.CharField('Chave do Carrinho', max_length=40, db_index=True)
    product = models.ForeignKey('catalog.Product', on_delete=models.CASCADE, verbose_name='Produto')
    quantity = models.PositiveIntegerField('Quantidade', default=1)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)

    objects = CartItemManager()

    class Meta:
        verbose_name = 'Item do Carrinho'
        verbose_name_plural = 'Itens dos Carrinhos'
        unique_together = (('cart_key', 'product'),)

    def __str__(self):
        return '{} [{}]'.format(self.product, self.quantity)


class OrderManager(models.Manager):
    
    def create_order(self, user, cart_items):
        order = self.create(user=user)

        for cart_item in cart_items:
            order_item = OrderItem.objects.create(
                order=order,
                quantity=cart_item.quantity,
                product=cart_item.product,
                price=cart_item.price,
            )

        return order


class Order(models.Model):
    
    STATUS_CHOICES = (
        (0, 'Aguardando Pagamento'),
        (1, 'Concluída'),
        (2, 'Cancelada'),
    )

    PAYMENT_OPTION_CHOICES = (
        ('deposit', 'Depósito'),
        ('pagseguro', 'PagSeguro'),
        ('paypal', 'PayPal'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuário', on_delete=models.PROTECT)
    status = models.IntegerField('Situação', choices=STATUS_CHOICES, default=0, blank=True)
    payment_option = models.CharField('Opção de Pagamento', choices=PAYMENT_OPTION_CHOICES, max_length=20, default='deposit')
    
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    objects = OrderManager()

    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'
    
    def __str__(self):
        return 'Pedido #{}'.format(self.pk)

    def products(self):
        # products = []        
        # for item in self.items.all():
        #     products.append(item.product)
        # return products
        products_ids = self.items.values_list('product')
        return Product.objects.filter(pk__in=products_ids)

    def total(self):
        aggregate_queryset = self.items.aggregate(
            total=models.Sum(
                models.F('price') * models.F('quantity'),
                output_field=models.DecimalField()
            )
        )

        return aggregate_queryset['total']


class OrderItem(models.Model):

    order = models.ForeignKey(Order, verbose_name='Pedido', related_name='items', on_delete=models.PROTECT)
    product = models.ForeignKey('catalog.Product', on_delete=models.CASCADE, verbose_name='Produto')
    quantity = models.PositiveIntegerField('Quantidade', default=1)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)

    class Meta:
        verbose_name = 'Item do pedido'
        verbose_name_plural = 'Itens dos pedidos'

    def __str__(self):
        return '[{}] {}'.format(self.order.pk, self.product)


def post_save_cart_item(instance, **kwargs):
    if instance.quantity < 1:
        instance.delete()


models.signals.post_save.connect(
    post_save_cart_item,
    sender=CartItem,
    dispatch_uid='post_save_cart_item'
)

checkout/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import RedirectView, TemplateView, ListView, DetailView
from django.forms import modelformset_factory
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin

from catalog.models import Product

from .models import CartItem, Order

# Create your views here.


class CreateCartItemView(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        product = get_object_or_404(Product, slug=self.kwargs['slug'])

        if self.request.session.session_key is None:
            self.request.session.save()

        cart_item, created = CartItem.objects.add_item(
            self.request.session.session_key,
            product,
        )

        if created:
            messages.success(self.request, 'Produto adicionado com sucesso!')
        else:
            messages.success(self.request, 'Produto atualizado com sucesso!')
        
        return reverse('checkout:cart_item')


class CartItemView(TemplateView):

    template_name = 'checkout/cart.html'


    def get_formset(self, clear=False):
        CartItemFormSet = modelformset_factory(
            CartItem,
            fields=('quantity',),
            can_delete=True,
            extra=0,
        )

        session_key = self.request.session.session_key

        if session_key:
            if clear:
                formset = CartItemFormSet(queryset=CartItem.objects.filter(cart_key=session_key))
            else:
                formset = CartItemFormSet(
                    queryset=CartItem.objects.filter(cart_key=session_key),
                    data=self.request.POST or None
                )
        else:
            formset = CartItemFormSet(queryset=CartItem.objects.none())

        return formset

    def get_context_data(self, **kwargs):
        context = super(CartItemView, self).get_context_data(**kwargs)
        context['formset'] = self.get_formset()
        return context

    def post(self, request, *args, **kwargs):
        formset = self.get_formset()
        context = self.get_context_data(**kwargs)

        if formset.is_valid():
            formset.save()
            messages.success(request, 'Carrinho atualizado com sucesso!')
            context['formset'] = self.get_formset(clear=True)

        return self.render_to_response(context)


class CheckoutView(LoginRequiredMixin, TemplateView):

    template_name = 'checkout/checkout.html'

    def get(self, request, *args, **kwargs):
        session_key = request.session.session_key

        if session_key and CartItem.objects.filter(cart_key=session_key).exists():
            cart_items = CartItem.objects.filter(cart_key=session_key)
            order = Order.objects.create_order(user=request.user, cart_items=cart_items)
        else:
            messages.info(request, 'Não há itens no carrinho de compras!')
            return redirect('checkout:cart_item')

        response = super(CheckoutView, self).get(request, *args, **kwargs)
        response.context_data['order'] = order

        return response


class OrderListView(LoginRequiredMixin, ListView):

    template_name = 'checkout/order_list.html'
    paginate_by = 10

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class OrderDetailView(LoginRequiredMixin, DetailView):
    
    template_name = 'checkout/order_detail.html'
    
    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


create_cartitem = CreateCartItemView.as_view()
cart_item = CartItemView.as_view()
checkout = CheckoutView.as_view()
order_list = OrderListView.as_view()
order_detail = OrderDetailView.as_view()

templates/checkout/cart.html
{% extends 'core/base.html' %}

{% load widget_tweaks %}

{% block title %}
    Carrinho de Compras | {{ block.super }}
{% endblock %}

{% block main %}
    <div class="row">
        <div class="col">
            <div class="page-header">
                <h1>Carrinho de Compras</h1>
            </div>

            <form class="" method="POST">
                {% csrf_token %}

                {{ formset.management_form }}

                <table class="table table-bordered">
                    <thead>
                        <th>ID</th>
                        <th>Nome</th>
                        <th>Preço</th>
                        <th style='width: 10%;'>Quantidade</th>
                        <th></th>
                    </thead>

                    <tbody>
                        {% for form in formset %}
                            <tr>
                                <td>{{ form.instance.product.pk }}</td>
                                <td>{{ form.instance.product }}</td>
                                <td>R$ {{ form.instance.price|floatformat:'2' }}</td>
                                <td>{% render_field form.quantity class='form-control' %}</td>
                                <td class="text-center">
                                    <button class="btn btn-danger btn-sm" value="on" type="submit" name="{{ form.DELETE.html_name }}">remover</button>
                                    {{ form.id }}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

                <p class="text-right">
                    <a href="{% url 'catalog:products' %}" class="btn btn-success float-left">Continuar Compras</a>
                    <button class="btn btn-dark" type="submit" name="button">Atualizar Carrinho</button>
                    <a href="{% url 'checkout:checkout' %}" class="btn btn-info">Finalizar Compra</a>
                </p>
            </form>
        </div>
    </div>
{% endblock %}

templates/checkout/checkout.html
{% extends 'core/base.html' %}

{% block title %}
    Finalização da Compra | {{ block.super }}
{% endblock %}

{% block main %}
    <div class="row">
        <div class="col">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'core:index' %}">Início</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'checkout:cart_item' %}">Carrinho de Compras</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Carrinho de Compras</li>
                </ol>
            </nav>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="page-header">
                <h1>Escolha a forma de pagamento</h1>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <p>Pedido #{{ order.pk }}</p>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-4 offset-md-2">
            <a href="#" class="btn btn-info">Pagar com PagSeguro</a>
        </div>

        <div class="col-md-4">
            <a href="#" class="btn btn-dark">Pagar com PayPal</a>
        </div>
    </div>
{% endblock %}

templates/checkout/order_detail.html
{% extends 'accounts/index.html' %}

{% block title %}
    Pedido #{{ order.pk }} | {{ block.super }}
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'checkout:order_list' %}">Meus Pedidos</a></li>
    <li class="breadcrumb-item active" aria-current="page">Pedido #{{ order.pk }}</li>
{% endblock %}

{% block listGroupMenu %}
    <a href="{% url 'accounts:index' %}" class="list-group-item list-group-item-action">Minha Conta</a>
    <a href="{% url 'accounts:update_user' %}" class="list-group-item list-group-item-action">Alterar Dados</a>
    <a href="{% url 'accounts:update_password' %}" class="list-group-item list-group-item-action">Alterar Senha</a>
    <a href="{% url 'checkout:order_list' %}" class="list-group-item list-group-item-action active">Meus Pedidos</a>
{% endblock %}

{% block accounts_container %}
    <dl class="row">
        <dt class="col-sm-6 text-right">Total</dt>
        <dd class="col-sm-6">R$ {{ object.total|floatformat:"2" }}</dd>

        <dt class="col-sm-6 text-right">Situação</dt>
        <dd class="col-sm-6">{{ object.get_status_display }}</dd>

        <dt class="col-sm-6 text-right">Data</dt>
        <dd class="col-sm-6">{{ object.created|date:"d/M/Y H:i" }}</dd>

        <dt class="col-sm-6 text-right">Meio de Pagamento</dt>
        <dd class="col-sm-6">{{ object.get_payment_option_display }}</dd>
    </dl>

    <br>

    <h3>Itens do Pedido</h3>
    <table class="table table-bordered table-striped table-sm">
        <caption>Detalhes do pedido</caption>

        <thead class="thead-dark">
            <th>Produto</th>
            <th class="text-center">Quantidade</th>
            <th>Preço</th>
        </thead>
        
        <tbody>
            {% for item in object.items.all %}
                <tr>
                    <td>{{ item.product }}</td>
                    <td class="text-center">{{ item.quantity }}</td>
                    <td>R$ {{ item.price|floatformat:"2" }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/checkout/order_list.html
{% extends 'accounts/index.html' %}

{% load pagination %}

{% block title %}
    Meus Pedidos | {{ block.super }}
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item active" aria-current="page">Meus Pedidos</li>
{% endblock %}

{% block listGroupMenu %}
    <a href="{% url 'accounts:index' %}" class="list-group-item list-group-item-action">Minha Conta</a>
    <a href="{% url 'accounts:update_user' %}" class="list-group-item list-group-item-action">Alterar Dados</a>
    <a href="{% url 'accounts:update_password' %}" class="list-group-item list-group-item-action">Alterar Senha</a>
    <a href="{% url 'checkout:order_list' %}" class="list-group-item list-group-item-action active">Meus Pedidos</a>
{% endblock %}

{% block accounts_container %}
    <table class="table table-bordered table-hover">
        <caption>Meus pedidos</caption>

        <thead class="thead-dark">
            <th>ID</th>
            <th>Produtos</th>
            <th>Situação</th>
            <th>Data</th>
        </thead>

        <tbody>
            {% for order in object_list %}
                <tr>
                    <td>
                        <a href="{% url 'checkout:order_detail' order.pk %}">#{{ order.pk }}</a>
                    </td>
                    <td>
                        {% for product in order.products %}
                            {{ product.name }}

                            {% if not forloop.last %}
                                <br>
                            {% endif %}
                        {% endfor %}
                    </td>
                    <td>
                        {{ order.get_status_display }}
                    </td>
                    <td>
                        {{ order.created|date:"d/M/Y" }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    {% pagination request paginator page_obj %}
{% endblock %}