catalog/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import (
    product_list,
    category,
    product,
)

app_name = 'catalog'

urlpatterns = [
    path('', product_list, name='products'),
    path('<slug:slug>/', category, name='category'),
    path('produtos/<slug:slug>/', product, name='product'),
]

checkout/urls.py
from django.urls import path

from .views import (
    create_cartitem,
    cart_item,
    checkout,
    order_list,
    order_detail,
)

app_name = 'checkout'

urlpatterns = [
    path('carrinho/adicionar/<slug:slug>/', create_cartitem, name='create_cartitem'),
    path('carrinho/', cart_item, name='cart_item'),
    path('finalizando/', checkout, name='checkout'),
    path('meus-pedidos/', order_list, name='order_list'),
    path('meus-pedidos/<int:pk>', order_detail, name='order_detail'),
]

core/urls.py
from django.urls import path

from .views import (
    index,
    contact,
)

app_name = 'core'

urlpatterns = [
    path('', index, name="index"),
    
    path('contato/', contact, name='contact'),
]

djangoecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('catalogo/', include('catalog.urls', namespace='catalog')),
    path('admin/', admin.site.urls, name='admin'),
]

catalog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Category(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100)

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:category', kwargs={'slug' : self.slug})


class Product(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100)
    category = models.ForeignKey('catalog.Category', verbose_name='Categoria', on_delete=models.PROTECT)
    description = models.TextField('Descrição', blank=True)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:product', kwargs={'slug' : self.slug})

catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic

from .models import Product, Category

# Create your views here.

class ProductsListView(generic.ListView):

    model = Product
    template_name = 'catalog/product_list.html'
    context_object_name = 'products'
    paginate_by = 3


class CategoryListView(generic.ListView):

    template_name = 'catalog/category.html'
    context_object_name = 'products'
    paginate_by = 3

    def get_queryset(self):
        # category = get_object_or_404(Category, slug = self.kwargs['slug'])
        # return Product.objects.filter(category=category)
        return Product.objects.filter(category__slug = self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['current_category'] = get_object_or_404(Category, slug = self.kwargs['slug'])
        return context


class ProductListView(generic.ListView):

    template_name = 'catalog/product.html'
    context_object_name = 'product'

    def get_queryset(self):
        return Product.objects.get(slug = self.kwargs['slug'])


product_list = ProductsListView.as_view()
category = CategoryListView.as_view()
product = ProductListView.as_view()

templates/catalog/_product.html
<div class="col-sm-4">
    <div class="img-thumbnail">
        <a href="{{ product.get_absolute_url }}">
            <img src="http://placehold.it/350x250" class="img-fluid" alt="Responsive image">
        </a>
        
        <div class="caption">
            <h3>{{ product }}</h3>
            <p>{{ product.description|linebreaks }}</p>
            
            <p>
                <a href="{{ product.get_absolute_url }}" class="btn btn-info" role="button">Detalhes</a>
                <a href="{% url 'checkout:create_cartitem' product.slug %}" class="btn btn-dark" role="button">Adicionar</a>
            </p>
        </div>
    </div>
</div>

templates/catalog/category.html
{% extends 'core/base.html' %}

{% load pagination %}

{% block title %}
    {{ current_category|capfirst }} | {{ block.super }}
{% endblock %}

{% block main %}
    <div class="row">
        <div class="col">
            <div class="page-header">
                <h1>{{ current_category|capfirst }}</h1>
            </div>
        </div>
    </div>

    <div class="row">
        {% for product in products %}
            {% include 'catalog/_product.html' %}
        {% endfor %}
    </div>
    
    {% pagination request paginator page_obj %}
{% endblock %}

templates/catalog/pagination.html
{% if page_obj.has_other_pages %}
    <div class="row">
        <div class="col">
            <nav aria-label="page navigation">
                <ul class="pagination">
                    {% for page in paginator.page_range %}
                        <li {% if page_obj.number == page %} class="page-item active" {% else %} class="page-item" {% endif %}>
                            <a class="page-link" href="?page={{ page }}{{ getvars }}">{{ page }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </nav>
        </div>
    </div>
{% endif %}

templates/catalog/product.html
{% extends 'core/base.html' %}

{% block title %}
    {{ product|capfirst }} | {{ block.super }}
{% endblock %}

{% block main %}
    <div class="row">
        <div class="col">
            <div class="page-header">
                <h1>{{ product|capfirst }}</h1>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-4">
            <img src="http://placehold.it/350x250" class="img-fluid img-thumbnail" alt="Responsive image">
        </div>

        <div class="col-sm-8">
            <p class="text-right">
                <a href="{% url 'checkout:create_cartitem' product.slug %}" class="btn btn-info">Adicionar ao Carrinho</a>
            </p>

            {{ product.description|linebreaks }}            
        </div>
    </div>
{% endblock %}

templates/catalog/product_list.html
{% extends 'core/base.html' %}

{% load pagination %}

{% block title %}
    Listagem de Produtos | {{ block.super }}
{% endblock %}

{% block main %}
    <div class="row">
        <div class="col">
            <div class="page-header">
                <h1>Produtos</h1>
            </div>
        </div>
    </div>

    <div class="row">
        {% for product in products %}
            {% include 'catalog/_product.html' %}
        {% endfor %}
    </div>

    {% pagination request paginator page_obj %}
{% endblock %}

templates/catalog/products.html
{% extends 'core/base.html' %}

{% block title %}
    Listagem de Produtos | {{ block.super }}
{% endblock %}

{% block main %}
    <div class="row">
        <div class="col">
            <div class="page-header">
                <h1>Produtos</h1>
            </div>
        </div>
    </div>

    <div class="row">
        {% for product in products %}
            <div class="col-sm-4">
                <div class="img-thumbnail">
                    <a href="{{ product.get_absolute_url }}">
                        <img src="http://placehold.it/350x250" class="img-fluid" alt="Responsive image">
                    </a>
                    
                    <div class="caption">
                        <h3>{{ product }}</h3>
                        <p>{{ product.description|linebreaks }}</p>
                        
                        <p>
                            <a href="{{ product.get_absolute_url }}" class="btn btn-info" role="button">Mais detalhes</a>
                            <a href="#" class="btn btn-dark" role="button">Button</a>
                        </p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}